# Generated by Django 5.0.6 on 2024-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='goal',
            field=models.TextField(default='test goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='tasks',
            field=models.ManyToManyField(to='project_manager.task'),
        ),
    ]
