# Generated by Django 5.0.6 on 2024-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_remove_session_notes_session_active_session_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
