# Generated by Django 5.0.6 on 2024-07-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='taskcontainer',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
