# Generated by Django 5.0.6 on 2024-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_category_is_default_category_order_project_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
