# Generated by Django 5.0.6 on 2024-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0009_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
