# Generated by Django 5.0.6 on 2024-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0010_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='goal',
            field=models.TextField(default='No goal', max_length=100),
        ),
    ]
